[package]
name = "sylphrena-input"
version = "0.1.0"
authors = ["Eirik Dale <ideauss@hotmail.com>"]
homepage = "https://github.com/ShardAi/sylphrena-source"
repository = "https://github.com/ShardAi/sylphrena-source"

[dependencies]
daemonize = "0.3.0"